"""
phase4_advisor_followup.py -- five direct advisor questions raised after
Phase 4 shipped, answered with numbers instead of argued from intuition,
and folded into Phase 4's own "Mentor Concerns -- Addressed" table and
Analysis section rather than a separate page. Each question maps to one
function below; run standalone, prints everything needed for the site
write-up.

1. Pre-event window: should it "stay" (fixed to the sequence anchor,
   current design) or "move" (re-anchor to every individual event's own
   date)? Quantifies what "move" would actually change.
2. avg_tone / tone_negative_score: do escalated and peaceful events
   actually differ on these, or does it look that way by chance at
   n=174? Welch's t-test (unequal variance, matches the class imbalance)
   plus Levene's test on the variances themselves.
3. Is the SVM (RBF) result in phase3_model_search.py overfitting?
   Direct train-vs-test comparison, not just eyeballing the test score.
4. Year-to-year drift: which features actually shift between 2021 and
   2024, with effect sizes, not just the interaction-model R^2 from
   phase3_time_varying.py.
5. Is GDELT coverage declining because the scraper is breaking, or
   because the pull was capped? Raw (pre-filter) row counts by year,
   not just the kept/dropped counts build_training_table_v2.py prints.
"""
import warnings
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score, roc_auc_score, brier_score_loss

warnings.filterwarnings("ignore")

FEATURE_COLS = [
    "avg_tone", "tone_positive_score", "tone_negative_score", "tone_polarity",
    "tone_activity_density", "tone_self_group_density", "tone_word_count",
    "goldstein_trend", "quad_class_ratio", "log_volume",
    "had_gkg_match", "had_events_match", "year_numeric",
]


def load_table():
    df = pd.read_csv("data/training_table_v2.csv", parse_dates=["event_date"])
    df["log_volume"] = np.log1p(df["volume_mention_spike"])
    df["had_gkg_match"] = df["had_gkg_match"].astype(int)
    df["had_events_match"] = df["had_events_match"].astype(int)
    df["year_numeric"] = df["year"] - 2020
    return df


def within_year_split(df):
    train_parts, test_parts = [], []
    for year, sub in df.groupby("year"):
        sub = sub.sort_values("event_date")
        cut = max(1, int(len(sub) * 0.75))
        train_parts.append(sub.iloc[:cut])
        test_parts.append(sub.iloc[cut:])
    train = pd.concat(train_parts).sort_values("event_date").reset_index(drop=True)
    test = pd.concat(test_parts).sort_values("event_date").reset_index(drop=True)
    return train, test


def q1_stay_vs_move():
    print("\n===== Q1: stay-time vs move-time pre-event window =====")
    df = load_table()
    in_seq = df["in_sequence"].sum()
    print(f"{in_seq}/{len(df)} events ({in_seq/len(df)*100:.1f}%) belong to a multi-event sequence "
          f"(same state, events <=5 days apart).")
    print("For those events, 'move' (each event keeps its own 7-day pre-window) would let the model "
          "see real news coverage OF the earlier event in the same wave as if it were ambient pre-event "
          "signal for the later one -- the later event's window would overlap the earlier event's own "
          "date. 'Stay' (current design) anchors every event in a sequence to the sequence's first date, "
          "so no event's window can include coverage generated by another labeled event.")
    print("Verdict: stay. The cost is a same-day-informativeness assumption for chained events; the "
          "alternative is straightforward label leakage for 17% of the dataset.")


def q2_tone_significance(train):
    print("\n===== Q2: avg_tone / tone_negative_score -- real difference or noise? =====")
    for col in ["avg_tone", "tone_negative_score"]:
        peaceful = train.loc[train["label_escalated"] == 0, col].dropna()
        escalated = train.loc[train["label_escalated"] == 1, col].dropna()
        t, p_mean = stats.ttest_ind(peaceful, escalated, equal_var=False)
        lev, p_var = stats.levene(peaceful, escalated)
        print(f"\n{col}: peaceful n={len(peaceful)} mean={peaceful.mean():.3f} sd={peaceful.std():.3f} | "
              f"escalated n={len(escalated)} mean={escalated.mean():.3f} sd={escalated.std():.3f}")
        print(f"  Welch's t-test on the means: t={t:.2f}, p={p_mean:.3f} -> "
              f"{'significant at .05' if p_mean < 0.05 else 'NOT significant at .05'}")
        print(f"  Levene's test on the variances: W={lev:.2f}, p={p_var:.3f} -> "
              f"{'variances differ' if p_var < 0.05 else 'variances not distinguishable'}")


def q3_svm_overfitting(train, test):
    print("\n===== Q3: is the RBF SVM overfitting? =====")
    X_train, y_train = train[FEATURE_COLS], train["label_escalated"]
    X_test, y_test = test[FEATURE_COLS], test["label_escalated"]
    pipe = Pipeline([("impute", SimpleImputer(strategy="median")), ("scale", StandardScaler()),
                      ("clf", SVC(kernel="rbf", C=1.0, gamma="scale", class_weight="balanced",
                                  probability=True, random_state=42))])
    pipe.fit(X_train, y_train)
    train_prob = pipe.predict_proba(X_train)[:, 1]
    test_prob = pipe.predict_proba(X_test)[:, 1]
    print(f"Train PR-AUC={average_precision_score(y_train, train_prob):.3f}  "
          f"ROC-AUC={roc_auc_score(y_train, train_prob):.3f}  Brier={brier_score_loss(y_train, train_prob):.3f}")
    print(f"Test  PR-AUC={average_precision_score(y_test, test_prob):.3f}  "
          f"ROC-AUC={roc_auc_score(y_test, test_prob):.3f}  Brier={brier_score_loss(y_test, test_prob):.3f}")
    print(f"Train predicted-prob range: [{train_prob.min():.3f}, {train_prob.max():.3f}], "
          f"{(train_prob >= 0.5).sum()}/{len(train_prob)} predicted positive")
    print(f"Test  predicted-prob range: [{test_prob.min():.3f}, {test_prob.max():.3f}], "
          f"{(test_prob >= 0.5).sum()}/{len(test_prob)} predicted positive (test true rate {y_test.mean():.1%})")
    gap = average_precision_score(y_train, train_prob) - average_precision_score(y_test, test_prob)
    print(f"Train-test PR-AUC gap: {gap:.3f} -- {'a real overfit gap' if gap > 0.15 else 'not a large train/test gap'}")
    print("If train and test PR-AUC track together and the failure is a same-direction squash of *both* "
          "toward 0.5 with the same class always predicted, that is an under-confident / miscalibrated "
          "margin, not memorization -- overfitting means train does well and test doesn't.")


def q4_year_drift(df):
    print("\n===== Q4: which features actually move between 2021 and 2024? =====")
    sub = df[df["year"].isin([2021, 2024])]
    cols = ["avg_tone", "tone_negative_score", "tone_word_count", "goldstein_trend",
            "quad_class_ratio", "log_volume"]
    rows = []
    for col in cols:
        g21 = sub.loc[sub["year"] == 2021, col].dropna()
        g24 = sub.loc[sub["year"] == 2024, col].dropna()
        if len(g21) < 2 or len(g24) < 2:
            continue
        pooled_sd = np.sqrt(((len(g21) - 1) * g21.std() ** 2 + (len(g24) - 1) * g24.std() ** 2) / (len(g21) + len(g24) - 2))
        cohens_d = (g24.mean() - g21.mean()) / pooled_sd if pooled_sd > 0 else float("nan")
        t, p = stats.ttest_ind(g21, g24, equal_var=False)
        rows.append((col, g21.mean(), g24.mean(), cohens_d, p))
    print(f"{'feature':28s} {'2021 mean':>10s} {'2024 mean':>10s} {'Cohen d':>9s} {'p':>7s}")
    for col, m21, m24, d, p in sorted(rows, key=lambda r: -abs(r[3])):
        flag = "  <-- large shift" if abs(d) > 0.8 else ("  <-- moderate" if abs(d) > 0.5 else "")
        print(f"{col:28s} {m21:10.3f} {m24:10.3f} {d:9.2f} {p:7.3f}{flag}")
    print("(n=99 in 2021 vs n=10 in 2024 -- treat 2024 numbers as suggestive, not confirmatory; "
          "reported for direction/magnitude, not as a hypothesis test with real power.)")


def q5_scraper_health():
    print("\n===== Q5: is the scraper breaking, or was the pull capped? =====")
    import json
    gkg = (json.loads(open("data/gdelt_sample_100.json", encoding="utf-8").read())
           + json.loads(open("data/gdelt_sample_2021_2025.json", encoding="utf-8").read())
           + json.loads(open("data/gdelt_sample_2021_2025_part2.json", encoding="utf-8").read())
           + json.loads(open("data/gdelt_gkg_missing_2024.json", encoding="utf-8").read())
           + json.loads(open("data/gdelt_gkg_missing_2023.json", encoding="utf-8").read()))
    acled = json.loads(open("data/acled_sample_255.json", encoding="utf-8").read())
    year_by_event = {e["event_id_cnty"]: e["year"] for e in acled}
    raw_by_year = {}
    for r in gkg:
        y = year_by_event.get(r["_acled_event_id"])
        if y is not None:
            raw_by_year[y] = raw_by_year.get(y, 0) + 1
    events_by_year = pd.Series([e["year"] for e in acled]).value_counts().sort_index()
    print(f"{'year':6s} {'events':>7s} {'raw GKG rows':>13s} {'raw rows/event':>15s}")
    for y in sorted(events_by_year.index):
        n_events = events_by_year[y]
        n_rows = raw_by_year.get(y, 0)
        print(f"{y:<6d} {n_events:7d} {n_rows:13d} {n_rows / n_events:15.1f}")
    print("Coverage %/year from build_training_table_v2.py: 2020=67.0%, 2021=47.5%, 2022=45.8%, "
          "2023=40.9%, 2024=50.0%. The gap is almost entirely 2020-vs-everything-else, which matches "
          "the documented, deliberate BigQuery cost cap on the 2021-2024 pull (see build script docstring) "
          "-- 2021->2024 coverage itself is flat within noise (47.5/45.8/40.9/50.0), not a decaying trend, "
          "so this reads as a budget/sampling-design artifact, not scraper decay.")


def main():
    df = load_table()
    q1_stay_vs_move()

    modeled = df[(df["had_gkg_match"] > 0) | (df["had_events_match"] > 0)].reset_index(drop=True)
    train, test = within_year_split(modeled)
    q2_tone_significance(train)
    q3_svm_overfitting(train, test)
    q4_year_drift(df)
    q5_scraper_health()


if __name__ == "__main__":
    main()
